//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMsrv
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Base", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMsrv.Customer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMsrv.Project))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMsrv.Contract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMsrv.Invoice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMsrv.InvoiceLine))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMsrv.Expense))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMsrv.ExpenseCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMsrv.Notification))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BMsrv.User))]
    public partial class Base : object
    {
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Customer : BMsrv.Base
    {
        
        private string AddressField;
        
        private string BusinessNameField;
        
        private string ContactNameField;
        
        private string EmailField;
        
        private string NotesField;
        
        private int OwnerIdField;
        
        private string PhoneField;
        
        private string PreferredCurrencyField;
        
        private string TaxIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessName
        {
            get
            {
                return this.BusinessNameField;
            }
            set
            {
                this.BusinessNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName
        {
            get
            {
                return this.ContactNameField;
            }
            set
            {
                this.ContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredCurrency
        {
            get
            {
                return this.PreferredCurrencyField;
            }
            set
            {
                this.PreferredCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxId
        {
            get
            {
                return this.TaxIdField;
            }
            set
            {
                this.TaxIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Project : BMsrv.Base
    {
        
        private System.Nullable<int> AssignedEmployeeIdField;
        
        private string CurrencyField;
        
        private int CustomerIdField;
        
        private string DescriptionField;
        
        private System.Nullable<System.DateTime> DueDateField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private string StatusField;
        
        private string TitleField;
        
        private decimal TotalBudgetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AssignedEmployeeId
        {
            get
            {
                return this.AssignedEmployeeIdField;
            }
            set
            {
                this.AssignedEmployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DueDate
        {
            get
            {
                return this.DueDateField;
            }
            set
            {
                this.DueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalBudget
        {
            get
            {
                return this.TotalBudgetField;
            }
            set
            {
                this.TotalBudgetField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contract", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Contract : BMsrv.Base
    {
        
        private string BodyField;
        
        private string ContractNumberField;
        
        private System.DateTime CreatedAtField;
        
        private string CurrencyField;
        
        private int CustomerIdField;
        
        private string PdfPathField;
        
        private int ProjectIdField;
        
        private System.Nullable<System.DateTime> SignedDateField;
        
        private string StatusField;
        
        private string TitleField;
        
        private decimal TotalAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractNumber
        {
            get
            {
                return this.ContractNumberField;
            }
            set
            {
                this.ContractNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PdfPath
        {
            get
            {
                return this.PdfPathField;
            }
            set
            {
                this.PdfPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectId
        {
            get
            {
                return this.ProjectIdField;
            }
            set
            {
                this.ProjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SignedDate
        {
            get
            {
                return this.SignedDateField;
            }
            set
            {
                this.SignedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAmount
        {
            get
            {
                return this.TotalAmountField;
            }
            set
            {
                this.TotalAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Invoice : BMsrv.Base
    {
        
        private System.Nullable<int> ContractIdField;
        
        private string CurrencyField;
        
        private int CustomerIdField;
        
        private System.DateTime DueDateField;
        
        private string InvoiceNumberField;
        
        private System.DateTime IssueDateField;
        
        private string NotesField;
        
        private System.Nullable<System.DateTime> PaidDateField;
        
        private System.Nullable<int> ProjectIdField;
        
        private string StatusField;
        
        private decimal SubtotalField;
        
        private decimal TotalField;
        
        private decimal VatAmountField;
        
        private double VatRateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ContractId
        {
            get
            {
                return this.ContractIdField;
            }
            set
            {
                this.ContractIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate
        {
            get
            {
                return this.DueDateField;
            }
            set
            {
                this.DueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber
        {
            get
            {
                return this.InvoiceNumberField;
            }
            set
            {
                this.InvoiceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssueDate
        {
            get
            {
                return this.IssueDateField;
            }
            set
            {
                this.IssueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PaidDate
        {
            get
            {
                return this.PaidDateField;
            }
            set
            {
                this.PaidDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProjectId
        {
            get
            {
                return this.ProjectIdField;
            }
            set
            {
                this.ProjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Subtotal
        {
            get
            {
                return this.SubtotalField;
            }
            set
            {
                this.SubtotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VatAmount
        {
            get
            {
                return this.VatAmountField;
            }
            set
            {
                this.VatAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VatRate
        {
            get
            {
                return this.VatRateField;
            }
            set
            {
                this.VatRateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceLine", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class InvoiceLine : BMsrv.Base
    {
        
        private string CurrencyField;
        
        private string DescriptionField;
        
        private int InvoiceIdField;
        
        private decimal LineTotalField;
        
        private double QuantityField;
        
        private decimal UnitPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceId
        {
            get
            {
                return this.InvoiceIdField;
            }
            set
            {
                this.InvoiceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LineTotal
        {
            get
            {
                return this.LineTotalField;
            }
            set
            {
                this.LineTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice
        {
            get
            {
                return this.UnitPriceField;
            }
            set
            {
                this.UnitPriceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Expense", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Expense : BMsrv.Base
    {
        
        private decimal AmountField;
        
        private System.Nullable<int> CategoryIdField;
        
        private string CurrencyField;
        
        private System.DateTime DateField;
        
        private string DescriptionField;
        
        private int OwnerIdField;
        
        private System.Nullable<int> ProjectIdField;
        
        private string ReceiptPathField;
        
        private decimal VatPaidField;
        
        private string VendorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CategoryId
        {
            get
            {
                return this.CategoryIdField;
            }
            set
            {
                this.CategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProjectId
        {
            get
            {
                return this.ProjectIdField;
            }
            set
            {
                this.ProjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptPath
        {
            get
            {
                return this.ReceiptPathField;
            }
            set
            {
                this.ReceiptPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VatPaid
        {
            get
            {
                return this.VatPaidField;
            }
            set
            {
                this.VatPaidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vendor
        {
            get
            {
                return this.VendorField;
            }
            set
            {
                this.VendorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpenseCategory", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class ExpenseCategory : BMsrv.Base
    {
        
        private bool IsVatDeductibleField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVatDeductible
        {
            get
            {
                return this.IsVatDeductibleField;
            }
            set
            {
                this.IsVatDeductibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Notification : BMsrv.Base
    {
        
        private System.DateTime CreatedAtField;
        
        private bool IsReadField;
        
        private string MessageField;
        
        private string NotificationTypeField;
        
        private System.Nullable<System.DateTime> ReadAtField;
        
        private string TitleField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRead
        {
            get
            {
                return this.IsReadField;
            }
            set
            {
                this.IsReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationType
        {
            get
            {
                return this.NotificationTypeField;
            }
            set
            {
                this.NotificationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReadAt
        {
            get
            {
                return this.ReadAtField;
            }
            set
            {
                this.ReadAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class User : BMsrv.Base
    {
        
        private string BusinessTypeField;
        
        private System.DateTime CreatedAtField;
        
        private string EmailField;
        
        private bool IsActiveField;
        
        private string PasswordHashField;
        
        private string PhoneField;
        
        private string PreferredCurrencyField;
        
        private string RoleField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessType
        {
            get
            {
                return this.BusinessTypeField;
            }
            set
            {
                this.BusinessTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash
        {
            get
            {
                return this.PasswordHashField;
            }
            set
            {
                this.PasswordHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredCurrency
        {
            get
            {
                return this.PreferredCurrencyField;
            }
            set
            {
                this.PreferredCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AllUsers", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="User")]
    public class AllUsers : System.Collections.Generic.List<BMsrv.User>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VatSummary", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class VatSummary : object
    {
        
        private string DisplayCurrencyField;
        
        private decimal ExpensesTotalField;
        
        private decimal IncomeTotalField;
        
        private int MonthField;
        
        private decimal VatCollectedField;
        
        private decimal VatDueField;
        
        private decimal VatPaidField;
        
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayCurrency
        {
            get
            {
                return this.DisplayCurrencyField;
            }
            set
            {
                this.DisplayCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ExpensesTotal
        {
            get
            {
                return this.ExpensesTotalField;
            }
            set
            {
                this.ExpensesTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IncomeTotal
        {
            get
            {
                return this.IncomeTotalField;
            }
            set
            {
                this.IncomeTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Month
        {
            get
            {
                return this.MonthField;
            }
            set
            {
                this.MonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VatCollected
        {
            get
            {
                return this.VatCollectedField;
            }
            set
            {
                this.VatCollectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VatDue
        {
            get
            {
                return this.VatDueField;
            }
            set
            {
                this.VatDueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VatPaid
        {
            get
            {
                return this.VatPaidField;
            }
            set
            {
                this.VatPaidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfitLoss", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class ProfitLoss : object
    {
        
        private string DisplayCurrencyField;
        
        private decimal ExpensesField;
        
        private decimal IncomeField;
        
        private decimal ProfitField;
        
        private decimal TaxSetAsideEstimateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayCurrency
        {
            get
            {
                return this.DisplayCurrencyField;
            }
            set
            {
                this.DisplayCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Expenses
        {
            get
            {
                return this.ExpensesField;
            }
            set
            {
                this.ExpensesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Income
        {
            get
            {
                return this.IncomeField;
            }
            set
            {
                this.IncomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Profit
        {
            get
            {
                return this.ProfitField;
            }
            set
            {
                this.ProfitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxSetAsideEstimate
        {
            get
            {
                return this.TaxSetAsideEstimateField;
            }
            set
            {
                this.TaxSetAsideEstimateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerRevenueRow", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class CustomerRevenueRow : object
    {
        
        private string BusinessNameField;
        
        private int CustomerIdField;
        
        private string DisplayCurrencyField;
        
        private decimal TotalInvoicedField;
        
        private decimal TotalPaidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessName
        {
            get
            {
                return this.BusinessNameField;
            }
            set
            {
                this.BusinessNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayCurrency
        {
            get
            {
                return this.DisplayCurrencyField;
            }
            set
            {
                this.DisplayCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalInvoiced
        {
            get
            {
                return this.TotalInvoicedField;
            }
            set
            {
                this.TotalInvoicedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPaid
        {
            get
            {
                return this.TotalPaidField;
            }
            set
            {
                this.TotalPaidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpenseBreakdownRow", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class ExpenseBreakdownRow : object
    {
        
        private string CategoryNameField;
        
        private string DisplayCurrencyField;
        
        private bool IsVatDeductibleField;
        
        private decimal TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName
        {
            get
            {
                return this.CategoryNameField;
            }
            set
            {
                this.CategoryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayCurrency
        {
            get
            {
                return this.DisplayCurrencyField;
            }
            set
            {
                this.DisplayCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVatDeductible
        {
            get
            {
                return this.IsVatDeductibleField;
            }
            set
            {
                this.IsVatDeductibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeRevenueRow", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class EmployeeRevenueRow : object
    {
        
        private string DisplayCurrencyField;
        
        private int EmployeeIdField;
        
        private string EmployeeNameField;
        
        private int ProjectsCountField;
        
        private decimal RevenueGeneratedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayCurrency
        {
            get
            {
                return this.DisplayCurrencyField;
            }
            set
            {
                this.DisplayCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId
        {
            get
            {
                return this.EmployeeIdField;
            }
            set
            {
                this.EmployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeName
        {
            get
            {
                return this.EmployeeNameField;
            }
            set
            {
                this.EmployeeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectsCount
        {
            get
            {
                return this.ProjectsCountField;
            }
            set
            {
                this.ProjectsCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RevenueGenerated
        {
            get
            {
                return this.RevenueGeneratedField;
            }
            set
            {
                this.RevenueGeneratedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BMsrv.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserPassword", ReplyAction="http://tempuri.org/IService1/CheckUserPasswordResponse")]
        System.Threading.Tasks.Task<bool> CheckUserPasswordAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserExist", ReplyAction="http://tempuri.org/IService1/CheckUserExistResponse")]
        System.Threading.Tasks.Task<bool> CheckUserExistAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserById", ReplyAction="http://tempuri.org/IService1/GetUserByIdResponse")]
        System.Threading.Tasks.Task<BMsrv.User> GetUserByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserId", ReplyAction="http://tempuri.org/IService1/GetUserIdResponse")]
        System.Threading.Tasks.Task<int> GetUserIdAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        System.Threading.Tasks.Task<bool> AddUserAsync(string username, string password, string email, string phone, string role, string preferredCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ResetPassword", ReplyAction="http://tempuri.org/IService1/ResetPasswordResponse")]
        System.Threading.Tasks.Task ResetPasswordAsync(int userId, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUserRole", ReplyAction="http://tempuri.org/IService1/UpdateUserRoleResponse")]
        System.Threading.Tasks.Task UpdateUserRoleAsync(int userId, string newRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPendingUsers", ReplyAction="http://tempuri.org/IService1/GetPendingUsersResponse")]
        System.Threading.Tasks.Task<BMsrv.User[]> GetPendingUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetUserActive", ReplyAction="http://tempuri.org/IService1/SetUserActiveResponse")]
        System.Threading.Tasks.Task SetUserActiveAsync(int userId, bool isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsOwner", ReplyAction="http://tempuri.org/IService1/IsOwnerResponse")]
        System.Threading.Tasks.Task<bool> IsOwnerAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUsers", ReplyAction="http://tempuri.org/IService1/GetAllUsersResponse")]
        System.Threading.Tasks.Task<BMsrv.AllUsers> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllEmployees", ReplyAction="http://tempuri.org/IService1/GetAllEmployeesResponse")]
        System.Threading.Tasks.Task<BMsrv.User[]> GetAllEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUserProfile", ReplyAction="http://tempuri.org/IService1/UpdateUserProfileResponse")]
        System.Threading.Tasks.Task UpdateUserProfileAsync(int userId, string email, string phone, string preferredCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetBusinessType", ReplyAction="http://tempuri.org/IService1/SetBusinessTypeResponse")]
        System.Threading.Tasks.Task SetBusinessTypeAsync(int userId, string businessType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCustomer", ReplyAction="http://tempuri.org/IService1/AddCustomerResponse")]
        System.Threading.Tasks.Task<int> AddCustomerAsync(BMsrv.Customer c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCustomer", ReplyAction="http://tempuri.org/IService1/UpdateCustomerResponse")]
        System.Threading.Tasks.Task UpdateCustomerAsync(BMsrv.Customer c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCustomer", ReplyAction="http://tempuri.org/IService1/DeleteCustomerResponse")]
        System.Threading.Tasks.Task DeleteCustomerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerById", ReplyAction="http://tempuri.org/IService1/GetCustomerByIdResponse")]
        System.Threading.Tasks.Task<BMsrv.Customer> GetCustomerByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomersForOwner", ReplyAction="http://tempuri.org/IService1/GetCustomersForOwnerResponse")]
        System.Threading.Tasks.Task<BMsrv.Customer[]> GetCustomersForOwnerAsync(int ownerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchCustomers", ReplyAction="http://tempuri.org/IService1/SearchCustomersResponse")]
        System.Threading.Tasks.Task<BMsrv.Customer[]> SearchCustomersAsync(string keyword, int ownerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProject", ReplyAction="http://tempuri.org/IService1/AddProjectResponse")]
        System.Threading.Tasks.Task<int> AddProjectAsync(BMsrv.Project p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProject", ReplyAction="http://tempuri.org/IService1/UpdateProjectResponse")]
        System.Threading.Tasks.Task UpdateProjectAsync(BMsrv.Project p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetProjectStatus", ReplyAction="http://tempuri.org/IService1/SetProjectStatusResponse")]
        System.Threading.Tasks.Task SetProjectStatusAsync(int projectId, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AssignEmployee", ReplyAction="http://tempuri.org/IService1/AssignEmployeeResponse")]
        System.Threading.Tasks.Task AssignEmployeeAsync(int projectId, int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProjectsByCustomer", ReplyAction="http://tempuri.org/IService1/GetProjectsByCustomerResponse")]
        System.Threading.Tasks.Task<BMsrv.Project[]> GetProjectsByCustomerAsync(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProjectsForEmployee", ReplyAction="http://tempuri.org/IService1/GetProjectsForEmployeeResponse")]
        System.Threading.Tasks.Task<BMsrv.Project[]> GetProjectsForEmployeeAsync(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProjectsByStatus", ReplyAction="http://tempuri.org/IService1/GetProjectsByStatusResponse")]
        System.Threading.Tasks.Task<BMsrv.Project[]> GetProjectsByStatusAsync(string status, int ownerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProjectById", ReplyAction="http://tempuri.org/IService1/GetProjectByIdResponse")]
        System.Threading.Tasks.Task<BMsrv.Project> GetProjectByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProjectAssignment", ReplyAction="http://tempuri.org/IService1/AddProjectAssignmentResponse")]
        System.Threading.Tasks.Task AddProjectAssignmentAsync(int projectId, int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveProjectAssignment", ReplyAction="http://tempuri.org/IService1/RemoveProjectAssignmentResponse")]
        System.Threading.Tasks.Task RemoveProjectAssignmentAsync(int projectId, int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProjectAssignees", ReplyAction="http://tempuri.org/IService1/GetProjectAssigneesResponse")]
        System.Threading.Tasks.Task<BMsrv.User[]> GetProjectAssigneesAsync(int projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateContract", ReplyAction="http://tempuri.org/IService1/CreateContractResponse")]
        System.Threading.Tasks.Task<int> CreateContractAsync(BMsrv.Contract c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateContract", ReplyAction="http://tempuri.org/IService1/UpdateContractResponse")]
        System.Threading.Tasks.Task UpdateContractAsync(BMsrv.Contract c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteContract", ReplyAction="http://tempuri.org/IService1/DeleteContractResponse")]
        System.Threading.Tasks.Task DeleteContractAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkContractSigned", ReplyAction="http://tempuri.org/IService1/MarkContractSignedResponse")]
        System.Threading.Tasks.Task MarkContractSignedAsync(int id, System.DateTime signedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetContractById", ReplyAction="http://tempuri.org/IService1/GetContractByIdResponse")]
        System.Threading.Tasks.Task<BMsrv.Contract> GetContractByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetContractsForOwner", ReplyAction="http://tempuri.org/IService1/GetContractsForOwnerResponse")]
        System.Threading.Tasks.Task<BMsrv.Contract[]> GetContractsForOwnerAsync(int ownerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetContractsByProject", ReplyAction="http://tempuri.org/IService1/GetContractsByProjectResponse")]
        System.Threading.Tasks.Task<BMsrv.Contract[]> GetContractsByProjectAsync(int projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetContractsByCustomer", ReplyAction="http://tempuri.org/IService1/GetContractsByCustomerResponse")]
        System.Threading.Tasks.Task<BMsrv.Contract[]> GetContractsByCustomerAsync(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GenerateContractPdf", ReplyAction="http://tempuri.org/IService1/GenerateContractPdfResponse")]
        System.Threading.Tasks.Task<byte[]> GenerateContractPdfAsync(int contractId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateInvoice", ReplyAction="http://tempuri.org/IService1/CreateInvoiceResponse")]
        System.Threading.Tasks.Task<int> CreateInvoiceAsync(BMsrv.Invoice inv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddInvoiceLine", ReplyAction="http://tempuri.org/IService1/AddInvoiceLineResponse")]
        System.Threading.Tasks.Task<int> AddInvoiceLineAsync(BMsrv.InvoiceLine line);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateInvoiceStatus", ReplyAction="http://tempuri.org/IService1/UpdateInvoiceStatusResponse")]
        System.Threading.Tasks.Task UpdateInvoiceStatusAsync(int invoiceId, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkInvoicePaid", ReplyAction="http://tempuri.org/IService1/MarkInvoicePaidResponse")]
        System.Threading.Tasks.Task MarkInvoicePaidAsync(int invoiceId, System.DateTime paidDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecalcInvoiceTotals", ReplyAction="http://tempuri.org/IService1/RecalcInvoiceTotalsResponse")]
        System.Threading.Tasks.Task RecalcInvoiceTotalsAsync(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoiceById", ReplyAction="http://tempuri.org/IService1/GetInvoiceByIdResponse")]
        System.Threading.Tasks.Task<BMsrv.Invoice> GetInvoiceByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoiceLines", ReplyAction="http://tempuri.org/IService1/GetInvoiceLinesResponse")]
        System.Threading.Tasks.Task<BMsrv.InvoiceLine[]> GetInvoiceLinesAsync(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoicesByCustomer", ReplyAction="http://tempuri.org/IService1/GetInvoicesByCustomerResponse")]
        System.Threading.Tasks.Task<BMsrv.Invoice[]> GetInvoicesByCustomerAsync(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUnpaidInvoices", ReplyAction="http://tempuri.org/IService1/GetUnpaidInvoicesResponse")]
        System.Threading.Tasks.Task<BMsrv.Invoice[]> GetUnpaidInvoicesAsync(int ownerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOverdueInvoices", ReplyAction="http://tempuri.org/IService1/GetOverdueInvoicesResponse")]
        System.Threading.Tasks.Task<BMsrv.Invoice[]> GetOverdueInvoicesAsync(int ownerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GenerateInvoicePdf", ReplyAction="http://tempuri.org/IService1/GenerateInvoicePdfResponse")]
        System.Threading.Tasks.Task<byte[]> GenerateInvoicePdfAsync(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddExpense", ReplyAction="http://tempuri.org/IService1/AddExpenseResponse")]
        System.Threading.Tasks.Task<int> AddExpenseAsync(BMsrv.Expense e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateExpense", ReplyAction="http://tempuri.org/IService1/UpdateExpenseResponse")]
        System.Threading.Tasks.Task UpdateExpenseAsync(BMsrv.Expense e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteExpense", ReplyAction="http://tempuri.org/IService1/DeleteExpenseResponse")]
        System.Threading.Tasks.Task DeleteExpenseAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExpensesByOwner", ReplyAction="http://tempuri.org/IService1/GetExpensesByOwnerResponse")]
        System.Threading.Tasks.Task<BMsrv.Expense[]> GetExpensesByOwnerAsync(int ownerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExpensesByCategory", ReplyAction="http://tempuri.org/IService1/GetExpensesByCategoryResponse")]
        System.Threading.Tasks.Task<BMsrv.Expense[]> GetExpensesByCategoryAsync(int ownerId, int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExpensesByPeriod", ReplyAction="http://tempuri.org/IService1/GetExpensesByPeriodResponse")]
        System.Threading.Tasks.Task<BMsrv.Expense[]> GetExpensesByPeriodAsync(int ownerId, System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExpenseCategories", ReplyAction="http://tempuri.org/IService1/GetExpenseCategoriesResponse")]
        System.Threading.Tasks.Task<BMsrv.ExpenseCategory[]> GetExpenseCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UploadReceipt", ReplyAction="http://tempuri.org/IService1/UploadReceiptResponse")]
        System.Threading.Tasks.Task<string> UploadReceiptAsync(int expenseId, byte[] fileBytes, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVatSummary", ReplyAction="http://tempuri.org/IService1/GetVatSummaryResponse")]
        System.Threading.Tasks.Task<BMsrv.VatSummary> GetVatSummaryAsync(int ownerId, int year, int month, string displayCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMonthlyTaxSetAside", ReplyAction="http://tempuri.org/IService1/GetMonthlyTaxSetAsideResponse")]
        System.Threading.Tasks.Task<decimal> GetMonthlyTaxSetAsideAsync(int ownerId, int year, int month, string displayCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProfitLoss", ReplyAction="http://tempuri.org/IService1/GetProfitLossResponse")]
        System.Threading.Tasks.Task<BMsrv.ProfitLoss> GetProfitLossAsync(int ownerId, System.DateTime from, System.DateTime to, string displayCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTopCustomersByRevenue", ReplyAction="http://tempuri.org/IService1/GetTopCustomersByRevenueResponse")]
        System.Threading.Tasks.Task<BMsrv.CustomerRevenueRow[]> GetTopCustomersByRevenueAsync(int ownerId, string displayCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExpenseBreakdown", ReplyAction="http://tempuri.org/IService1/GetExpenseBreakdownResponse")]
        System.Threading.Tasks.Task<BMsrv.ExpenseBreakdownRow[]> GetExpenseBreakdownAsync(int ownerId, System.DateTime from, System.DateTime to, string displayCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployeeRevenueReport", ReplyAction="http://tempuri.org/IService1/GetEmployeeRevenueReportResponse")]
        System.Threading.Tasks.Task<BMsrv.EmployeeRevenueRow[]> GetEmployeeRevenueReportAsync(int ownerId, string displayCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCashFlowForecast", ReplyAction="http://tempuri.org/IService1/GetCashFlowForecastResponse")]
        System.Threading.Tasks.Task<BMsrv.ProfitLoss[]> GetCashFlowForecastAsync(int ownerId, int months, string displayCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EnsureOverdueNotifications", ReplyAction="http://tempuri.org/IService1/EnsureOverdueNotificationsResponse")]
        System.Threading.Tasks.Task<int> EnsureOverdueNotificationsAsync(int ownerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        System.Threading.Tasks.Task<double> GetExchangeRateAsync(string from, string to, System.DateTime asOfDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetExchangeRate", ReplyAction="http://tempuri.org/IService1/SetExchangeRateResponse")]
        System.Threading.Tasks.Task SetExchangeRateAsync(string from, string to, double rate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSupportedCurrencies", ReplyAction="http://tempuri.org/IService1/GetSupportedCurrenciesResponse")]
        System.Threading.Tasks.Task<string[]> GetSupportedCurrenciesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendNotification", ReplyAction="http://tempuri.org/IService1/SendNotificationResponse")]
        System.Threading.Tasks.Task<int> SendNotificationAsync(BMsrv.Notification n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserNotifications", ReplyAction="http://tempuri.org/IService1/GetUserNotificationsResponse")]
        System.Threading.Tasks.Task<BMsrv.Notification[]> GetUserNotificationsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUnreadNotificationCount", ReplyAction="http://tempuri.org/IService1/GetUnreadNotificationCountResponse")]
        System.Threading.Tasks.Task<int> GetUnreadNotificationCountAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkNotificationAsRead", ReplyAction="http://tempuri.org/IService1/MarkNotificationAsReadResponse")]
        System.Threading.Tasks.Task MarkNotificationAsReadAsync(int notificationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkAllNotificationsAsRead", ReplyAction="http://tempuri.org/IService1/MarkAllNotificationsAsReadResponse")]
        System.Threading.Tasks.Task MarkAllNotificationsAsReadAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteNotification", ReplyAction="http://tempuri.org/IService1/DeleteNotificationResponse")]
        System.Threading.Tasks.Task DeleteNotificationAsync(int notificationId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IService1Channel : BMsrv.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BMsrv.IService1>, BMsrv.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserPasswordAsync(string username, string password)
        {
            return base.Channel.CheckUserPasswordAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserExistAsync(string username)
        {
            return base.Channel.CheckUserExistAsync(username);
        }
        
        public System.Threading.Tasks.Task<BMsrv.User> GetUserByIdAsync(int id)
        {
            return base.Channel.GetUserByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> GetUserIdAsync(string username)
        {
            return base.Channel.GetUserIdAsync(username);
        }
        
        public System.Threading.Tasks.Task<bool> AddUserAsync(string username, string password, string email, string phone, string role, string preferredCurrency)
        {
            return base.Channel.AddUserAsync(username, password, email, phone, role, preferredCurrency);
        }
        
        public System.Threading.Tasks.Task ResetPasswordAsync(int userId, string newPassword)
        {
            return base.Channel.ResetPasswordAsync(userId, newPassword);
        }
        
        public System.Threading.Tasks.Task UpdateUserRoleAsync(int userId, string newRole)
        {
            return base.Channel.UpdateUserRoleAsync(userId, newRole);
        }
        
        public System.Threading.Tasks.Task<BMsrv.User[]> GetPendingUsersAsync()
        {
            return base.Channel.GetPendingUsersAsync();
        }
        
        public System.Threading.Tasks.Task SetUserActiveAsync(int userId, bool isActive)
        {
            return base.Channel.SetUserActiveAsync(userId, isActive);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(int userId)
        {
            return base.Channel.DeleteUserAsync(userId);
        }
        
        public System.Threading.Tasks.Task<bool> IsOwnerAsync(string username)
        {
            return base.Channel.IsOwnerAsync(username);
        }
        
        public System.Threading.Tasks.Task<BMsrv.AllUsers> GetAllUsersAsync()
        {
            return base.Channel.GetAllUsersAsync();
        }
        
        public System.Threading.Tasks.Task<BMsrv.User[]> GetAllEmployeesAsync()
        {
            return base.Channel.GetAllEmployeesAsync();
        }
        
        public System.Threading.Tasks.Task UpdateUserProfileAsync(int userId, string email, string phone, string preferredCurrency)
        {
            return base.Channel.UpdateUserProfileAsync(userId, email, phone, preferredCurrency);
        }
        
        public System.Threading.Tasks.Task SetBusinessTypeAsync(int userId, string businessType)
        {
            return base.Channel.SetBusinessTypeAsync(userId, businessType);
        }
        
        public System.Threading.Tasks.Task<int> AddCustomerAsync(BMsrv.Customer c)
        {
            return base.Channel.AddCustomerAsync(c);
        }
        
        public System.Threading.Tasks.Task UpdateCustomerAsync(BMsrv.Customer c)
        {
            return base.Channel.UpdateCustomerAsync(c);
        }
        
        public System.Threading.Tasks.Task DeleteCustomerAsync(int id)
        {
            return base.Channel.DeleteCustomerAsync(id);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Customer> GetCustomerByIdAsync(int id)
        {
            return base.Channel.GetCustomerByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Customer[]> GetCustomersForOwnerAsync(int ownerId)
        {
            return base.Channel.GetCustomersForOwnerAsync(ownerId);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Customer[]> SearchCustomersAsync(string keyword, int ownerId)
        {
            return base.Channel.SearchCustomersAsync(keyword, ownerId);
        }
        
        public System.Threading.Tasks.Task<int> AddProjectAsync(BMsrv.Project p)
        {
            return base.Channel.AddProjectAsync(p);
        }
        
        public System.Threading.Tasks.Task UpdateProjectAsync(BMsrv.Project p)
        {
            return base.Channel.UpdateProjectAsync(p);
        }
        
        public System.Threading.Tasks.Task SetProjectStatusAsync(int projectId, string status)
        {
            return base.Channel.SetProjectStatusAsync(projectId, status);
        }
        
        public System.Threading.Tasks.Task AssignEmployeeAsync(int projectId, int employeeId)
        {
            return base.Channel.AssignEmployeeAsync(projectId, employeeId);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Project[]> GetProjectsByCustomerAsync(int customerId)
        {
            return base.Channel.GetProjectsByCustomerAsync(customerId);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Project[]> GetProjectsForEmployeeAsync(int employeeId)
        {
            return base.Channel.GetProjectsForEmployeeAsync(employeeId);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Project[]> GetProjectsByStatusAsync(string status, int ownerId)
        {
            return base.Channel.GetProjectsByStatusAsync(status, ownerId);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Project> GetProjectByIdAsync(int id)
        {
            return base.Channel.GetProjectByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task AddProjectAssignmentAsync(int projectId, int employeeId)
        {
            return base.Channel.AddProjectAssignmentAsync(projectId, employeeId);
        }
        
        public System.Threading.Tasks.Task RemoveProjectAssignmentAsync(int projectId, int employeeId)
        {
            return base.Channel.RemoveProjectAssignmentAsync(projectId, employeeId);
        }
        
        public System.Threading.Tasks.Task<BMsrv.User[]> GetProjectAssigneesAsync(int projectId)
        {
            return base.Channel.GetProjectAssigneesAsync(projectId);
        }
        
        public System.Threading.Tasks.Task<int> CreateContractAsync(BMsrv.Contract c)
        {
            return base.Channel.CreateContractAsync(c);
        }
        
        public System.Threading.Tasks.Task UpdateContractAsync(BMsrv.Contract c)
        {
            return base.Channel.UpdateContractAsync(c);
        }
        
        public System.Threading.Tasks.Task DeleteContractAsync(int id)
        {
            return base.Channel.DeleteContractAsync(id);
        }
        
        public System.Threading.Tasks.Task MarkContractSignedAsync(int id, System.DateTime signedDate)
        {
            return base.Channel.MarkContractSignedAsync(id, signedDate);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Contract> GetContractByIdAsync(int id)
        {
            return base.Channel.GetContractByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Contract[]> GetContractsForOwnerAsync(int ownerId)
        {
            return base.Channel.GetContractsForOwnerAsync(ownerId);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Contract[]> GetContractsByProjectAsync(int projectId)
        {
            return base.Channel.GetContractsByProjectAsync(projectId);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Contract[]> GetContractsByCustomerAsync(int customerId)
        {
            return base.Channel.GetContractsByCustomerAsync(customerId);
        }
        
        public System.Threading.Tasks.Task<byte[]> GenerateContractPdfAsync(int contractId)
        {
            return base.Channel.GenerateContractPdfAsync(contractId);
        }
        
        public System.Threading.Tasks.Task<int> CreateInvoiceAsync(BMsrv.Invoice inv)
        {
            return base.Channel.CreateInvoiceAsync(inv);
        }
        
        public System.Threading.Tasks.Task<int> AddInvoiceLineAsync(BMsrv.InvoiceLine line)
        {
            return base.Channel.AddInvoiceLineAsync(line);
        }
        
        public System.Threading.Tasks.Task UpdateInvoiceStatusAsync(int invoiceId, string status)
        {
            return base.Channel.UpdateInvoiceStatusAsync(invoiceId, status);
        }
        
        public System.Threading.Tasks.Task MarkInvoicePaidAsync(int invoiceId, System.DateTime paidDate)
        {
            return base.Channel.MarkInvoicePaidAsync(invoiceId, paidDate);
        }
        
        public System.Threading.Tasks.Task RecalcInvoiceTotalsAsync(int invoiceId)
        {
            return base.Channel.RecalcInvoiceTotalsAsync(invoiceId);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Invoice> GetInvoiceByIdAsync(int id)
        {
            return base.Channel.GetInvoiceByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<BMsrv.InvoiceLine[]> GetInvoiceLinesAsync(int invoiceId)
        {
            return base.Channel.GetInvoiceLinesAsync(invoiceId);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Invoice[]> GetInvoicesByCustomerAsync(int customerId)
        {
            return base.Channel.GetInvoicesByCustomerAsync(customerId);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Invoice[]> GetUnpaidInvoicesAsync(int ownerId)
        {
            return base.Channel.GetUnpaidInvoicesAsync(ownerId);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Invoice[]> GetOverdueInvoicesAsync(int ownerId)
        {
            return base.Channel.GetOverdueInvoicesAsync(ownerId);
        }
        
        public System.Threading.Tasks.Task<byte[]> GenerateInvoicePdfAsync(int invoiceId)
        {
            return base.Channel.GenerateInvoicePdfAsync(invoiceId);
        }
        
        public System.Threading.Tasks.Task<int> AddExpenseAsync(BMsrv.Expense e)
        {
            return base.Channel.AddExpenseAsync(e);
        }
        
        public System.Threading.Tasks.Task UpdateExpenseAsync(BMsrv.Expense e)
        {
            return base.Channel.UpdateExpenseAsync(e);
        }
        
        public System.Threading.Tasks.Task DeleteExpenseAsync(int id)
        {
            return base.Channel.DeleteExpenseAsync(id);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Expense[]> GetExpensesByOwnerAsync(int ownerId)
        {
            return base.Channel.GetExpensesByOwnerAsync(ownerId);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Expense[]> GetExpensesByCategoryAsync(int ownerId, int categoryId)
        {
            return base.Channel.GetExpensesByCategoryAsync(ownerId, categoryId);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Expense[]> GetExpensesByPeriodAsync(int ownerId, System.DateTime from, System.DateTime to)
        {
            return base.Channel.GetExpensesByPeriodAsync(ownerId, from, to);
        }
        
        public System.Threading.Tasks.Task<BMsrv.ExpenseCategory[]> GetExpenseCategoriesAsync()
        {
            return base.Channel.GetExpenseCategoriesAsync();
        }
        
        public System.Threading.Tasks.Task<string> UploadReceiptAsync(int expenseId, byte[] fileBytes, string fileName)
        {
            return base.Channel.UploadReceiptAsync(expenseId, fileBytes, fileName);
        }
        
        public System.Threading.Tasks.Task<BMsrv.VatSummary> GetVatSummaryAsync(int ownerId, int year, int month, string displayCurrency)
        {
            return base.Channel.GetVatSummaryAsync(ownerId, year, month, displayCurrency);
        }
        
        public System.Threading.Tasks.Task<decimal> GetMonthlyTaxSetAsideAsync(int ownerId, int year, int month, string displayCurrency)
        {
            return base.Channel.GetMonthlyTaxSetAsideAsync(ownerId, year, month, displayCurrency);
        }
        
        public System.Threading.Tasks.Task<BMsrv.ProfitLoss> GetProfitLossAsync(int ownerId, System.DateTime from, System.DateTime to, string displayCurrency)
        {
            return base.Channel.GetProfitLossAsync(ownerId, from, to, displayCurrency);
        }
        
        public System.Threading.Tasks.Task<BMsrv.CustomerRevenueRow[]> GetTopCustomersByRevenueAsync(int ownerId, string displayCurrency)
        {
            return base.Channel.GetTopCustomersByRevenueAsync(ownerId, displayCurrency);
        }
        
        public System.Threading.Tasks.Task<BMsrv.ExpenseBreakdownRow[]> GetExpenseBreakdownAsync(int ownerId, System.DateTime from, System.DateTime to, string displayCurrency)
        {
            return base.Channel.GetExpenseBreakdownAsync(ownerId, from, to, displayCurrency);
        }
        
        public System.Threading.Tasks.Task<BMsrv.EmployeeRevenueRow[]> GetEmployeeRevenueReportAsync(int ownerId, string displayCurrency)
        {
            return base.Channel.GetEmployeeRevenueReportAsync(ownerId, displayCurrency);
        }
        
        public System.Threading.Tasks.Task<BMsrv.ProfitLoss[]> GetCashFlowForecastAsync(int ownerId, int months, string displayCurrency)
        {
            return base.Channel.GetCashFlowForecastAsync(ownerId, months, displayCurrency);
        }
        
        public System.Threading.Tasks.Task<int> EnsureOverdueNotificationsAsync(int ownerId)
        {
            return base.Channel.EnsureOverdueNotificationsAsync(ownerId);
        }
        
        public System.Threading.Tasks.Task<double> GetExchangeRateAsync(string from, string to, System.DateTime asOfDate)
        {
            return base.Channel.GetExchangeRateAsync(from, to, asOfDate);
        }
        
        public System.Threading.Tasks.Task SetExchangeRateAsync(string from, string to, double rate)
        {
            return base.Channel.SetExchangeRateAsync(from, to, rate);
        }
        
        public System.Threading.Tasks.Task<string[]> GetSupportedCurrenciesAsync()
        {
            return base.Channel.GetSupportedCurrenciesAsync();
        }
        
        public System.Threading.Tasks.Task<int> SendNotificationAsync(BMsrv.Notification n)
        {
            return base.Channel.SendNotificationAsync(n);
        }
        
        public System.Threading.Tasks.Task<BMsrv.Notification[]> GetUserNotificationsAsync(int userId)
        {
            return base.Channel.GetUserNotificationsAsync(userId);
        }
        
        public System.Threading.Tasks.Task<int> GetUnreadNotificationCountAsync(int userId)
        {
            return base.Channel.GetUnreadNotificationCountAsync(userId);
        }
        
        public System.Threading.Tasks.Task MarkNotificationAsReadAsync(int notificationId)
        {
            return base.Channel.MarkNotificationAsReadAsync(notificationId);
        }
        
        public System.Threading.Tasks.Task MarkAllNotificationsAsReadAsync(int userId)
        {
            return base.Channel.MarkAllNotificationsAsReadAsync(userId);
        }
        
        public System.Threading.Tasks.Task DeleteNotificationAsync(int notificationId)
        {
            return base.Channel.DeleteNotificationAsync(notificationId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WcfServiceLibrary1/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
